### ISSUE TITLE
Heatmap using weights of Moving Averages of tweets

### ISSUE THREAD

**Issue by vcuspinera** [vcuspinera/Canada_response_covid#4]
@cuspime made the next comment about the heat map shared in the main [README.md](https://github.com/vcuspinera/Canada_response_covid/tree/a7bdf4226197a7c0b2104ade54f6ce537eb5f20f) file in the _EDA_ section: 
> _"maybe some moving average here would be better? a 3 day window should suffice although a 7 days window would help remove weekly seasonality."_

<br>

Here is how it looks the heat map with weights of Moving Averages (MA) of tweets per day by account using different window time of 7, 5 and 3 days. __I would suggest using 7 or 5 days, what are your thoughts Leo?__

MA with window of __7 days__:
<img width="985" alt="image" src="https://user-images.githubusercontent.com/53915521/110745718-4f2f2500-8201-11eb-80bb-4ce165f85d22.png">

MA with window of __5 days__:
<img width="985" alt="image" src="https://user-images.githubusercontent.com/53915521/110745757-6110c800-8201-11eb-95d7-732713d98ad4.png">

MA with window of __3 days__:
<img width="985" alt="image" src="https://user-images.githubusercontent.com/53915521/110745796-70901100-8201-11eb-8e9e-9e7120dd5085.png">

**Comment by vcuspinera** [comment]
Finally I use the 7-day window for the Heatmap with weights of MA of number of tweets, but we can change depending on your comments Leo.

**Comment by cuspime** [comment]
Due to fundamental seasonality reasons, I think the 7 days MA is better. 
However, it seems like the weights are not independent. I thought you were normalising them independently but (as I understand it) this would put the max and min colours on all accounts to be the same? Or is it the Sum of all colours that adds up to the same?

**Comment by vcuspinera** [comment]
The weighs are independent by account, so each account has it's own maximum and minimum. This means that if we use the previous plot from the README file with weights of tweets by account, each row of the Heatmap (that represent an account)  add up to 1.

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/53915521/110808774-ecae4700-8249-11eb-9cf8-4ffc156410c4.png">

In the other hand, for the new plot were we use weights of Moving Averages (MA), as well as the previous plot each row represent an account, however, the sum of each row should be close to 1 -but not exactly 1.0-

For this heatmap the MA and weights were are calculated for each account as:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/53915521/110800743-1fecd800-8242-11eb-92d7-9573fc260238.png">

 ...where *MA_t* is the Moving Average of the day *t*, and *w_t* is the weight of Moving Average of day *t*.  

<br>

Just to understand a somewhat better, we use weights by account because the users published a lot more tweets mentioning _Canada_ and _JustinTrudeau_ accounts, than _CanadaPM_ and _GovCanHealth_ accounts. Here is how it looks if you present a heatmap with the number of tweets per day by account:

<img width="946" alt="image" src="https://user-images.githubusercontent.com/53915521/110799134-75c08080-8240-11eb-9588-14a6721caa1e.png">

Also, there are more details of the evolution of the presented Heatmap in the [EDA Jupiter Notebook of this repo](https://github.com/vcuspinera/Canada_response_covid/blob/master/src/eda.ipynb).

**Comment by vcuspinera** [comment]
Following our conversation, I also prepared the heat map applying normalization using min and max values (instead of weights) of the Moving Average of tweets by account and day, with would be the heatmap plot that printed in the main Readme file of this repo.

<img width="931" alt="image" src="https://user-images.githubusercontent.com/53915521/110854609-d4a2eb80-827a-11eb-81fb-b1a22eda3d80.png">
