### ISSUE TITLE
Leo's comments on Sentiment Analysis

### ISSUE THREAD

**Issue by vcuspinera** [vcuspinera/Canada_response_covid#5]
Here are some additional comments from @cuspime made in the main [README.md](https://github.com/vcuspinera/Canada_response_covid/blob/a7bdf4226197a7c0b2104ade54f6ce537eb5f20f/README.md) in the __Sentiment Analysis__ section, in specific about the polarity and subjectivity plots:

- [x] **1.** I think a log scale for this very plot would be better, cause they're just too close to each other and the range of values is very big.
- [x] **2.** There are some subjectivity outliers around 0. Is this normal???
- [x] **3.** More importantly,here I would do something slightly different. I would not take the tweets before and after and divide them in 2 like this. I think I would rather see a time series. So, I would prefer to see medians with bands that move through time (with a window average if it helps). This would help me better to "see" what happened. Maybe the difference was huge within 3 days and then it went back to normal?

**Comment by cuspime** [comment]
I can take a look at the time series bit of this and show it to you these coming days.

**Comment by vcuspinera** [comment]
Following with the questions:
1. ~~I will attend this point soon.~~ Done
2. ~~We can look closer to tweets with subjectivity equals to 0, to understand why this value is high.~~
3. ~~For the third point I would like to keep the analysis divided in two groups given that the original hypothesis is that the announcement day divide the sentiment of tweets in two groups. However, It would be good if we complement this with an additional time series analysis.~~

**Comment by vcuspinera** [comment]
I will add these chores to the TODO list.

**Comment by vcuspinera** [comment]
Done.
